### ISSUE TITLE
Secondary display flicker when closing application

### ISSUE THREAD

**Issue by adamalfath** [castle-engine/view3dscene#85]
In dual screen setup, my secondary screen flickers/blanks for about 1-2 seconds when closing the application. Is this expected?

OS: Win 10 22H2 19045.3693

**Comment by michaliskambi** [comment]
OS may do arbitrary things when OpenGL application stops, and I guess in this case it may switch the display from using "dedicated GPU" (like Nvidia or Radeon) and "low-end GPU" (like Intel). View3dscene requests to use "dedicated GPU" to be fast when rendering demanding 3D content. See https://castle-engine.io/dedicated_gpu for more details. I would guess you have a laptop with 2 GPUs.

I cannot reproduce it on my laptop (also with 2 GPUs) but it may be specific to your particular drivers, GPU models etc.

I'm afraid we cannot really do anything with it on our side. I guess that any windowed application using OpenGL and requesting "dedicated GPU" will suffer from the same artifact on your system.

Some standard things I would advise:

- Make sure you have the latest GPU (Nvidia etc.) GPU drivers installed.
- You may consider to just switch your system to *always* use the dedicated GPU. This should make the flickering go away, but then using always the dedicated GPU means your laptop battery will not last as long. You can search Internet for something like "windows force dedicated gpu", there are various solutions:
   - https://superuser.com/questions/1439471/how-can-i-force-my-dedicated-gpu-to-handle-all-applications-or-disable-my-integr
   - https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-force-windows-10-to-only-use-my/efaf113e-09a2-44ab-9e53-73a1d29c6ba0
   - https://techcult.com/how-to-force-windows-to-use-dedicated-graphics/

I'm closing the issue. Sorry that we cannot deal with it better, but it's just not something we can fix on view3dscene / Castle Game Engine side. We just use OpenGL context with "dedicated GPU".

**Comment by michaliskambi** [comment]
Following your suggestion from Discord:

For test: here's view3dscene version, for Windows 64-bit, that doesn't request dedicated GPU.

[view3dscene-4.3.0-win64-x86_64.zip](https://github.com/castle-engine/view3dscene/files/13450205/view3dscene-4.3.0-win64-x86_64.zip)

Done by just executing

```
castle-engine --compiler-option=-dCASTLE_NO_FORCE_DEDICATED_GPU --os=win64 --cpu=x86_64 package
```

in latest view3dscene source code tree. I cannot really guarantee that it will affect the outcome (system can decide to use dedicated GPU anyway, e.g. because it is OpenGL application; or maybe the decision is dictated by the need to have some frequency of display) but it is worth trying, IMO.

**Comment by adamalfath** [comment]
Unfortunately, I didn't see any difference from the old one. I also tried specifying the app to run on a built-in GPU but still didn't resolve it.

I'll live with it. Besides that, the app is very much usable.
Thank you very much for taking the time to compile it. I appreciate the answer and help.
